export const MOVIE_GENRES_GET_REQUEST = 'MOVIE_GENRES_GET_REQUEST';
export const MOVIE_GENRES_GET_SUCCESS = 'MOVIE_GENRES_GET_SUCCESS';

export const MOVIES_BY_GENRES_GET_REQUEST = 'MOVIES_BY_GENRES_GET_REQUEST';
export const MOVIES_BY_GENRES_GET_SUCCESS = 'MOVIES_BY_GENRES_GET_SUCCESS';

export const MOVIES_FEATURED_GET_REQUEST = 'MOVIES_FEATURED_GET_REQUEST';
export const MOVIES_FEATURED_GET_SUCCESS = 'MOVIES_FEATURED_GET_SUCCESS';

export const MOVIE_DETAIL_CLEAR = 'MOVIE_DETAIL_CLEAR';
export const MOVIE_DETAIL_GET_REQUEST = 'MOVIE_DETAIL_GET_REQUEST';
export const MOVIE_DETAIL_GET_SUCCESS = 'MOVIE_DETAIL_GET_SUCCESS';
