export const MOVIE_GENRES_GET_REQUEST = 'MOVIE_GENRES_GET_REQUEST';
export const MOVIE_GENRES_GET_SUCCESS = 'MOVIE_GENRES_GET_SUCCESS';
export const MOVIE_GENRES_GET_FAILURE = 'MOVIE_GENRES_GET_FAILURE';

export const MOVIES_BY_GENRES_GET_REQUEST = 'MOVIES_BY_GENRES_GET_REQUEST';
export const MOVIES_BY_GENRES_GET_SUCCESS = 'MOVIES_BY_GENRES_GET_SUCCESS';
export const MOVIES_BY_GENRES_GET_FAILURE = 'MOVIES_BY_GENRES_GET_FAILURE';

export const MOVIES_FEATURED_GET_REQUEST = 'MOVIES_FEATURED_GET_REQUEST';
export const MOVIES_FEATURED_GET_SUCCESS = 'MOVIES_FEATURED_GET_SUCCESS';
export const MOVIES_FEATURED_GET_FAILURE = 'MOVIES_FEATURED_GET_FAILURE';

export const MOVIE_DETAIL_CLEAR = 'MOVIE_DETAIL_CLEAR';
export const MOVIE_DETAIL_GET_REQUEST = 'MOVIE_DETAIL_GET_REQUEST';
export const MOVIE_DETAIL_GET_SUCCESS = 'MOVIE_DETAIL_GET_SUCCESS';
export const MOVIE_DETAIL_GET_FAILURE = 'MOVIE_DETAIL_GET_FAILURE';

export const MOVIE_RATE = 'MOVIE_RATE';
export const MOVIE_RATE_SUCCESS = 'MOVIE_RATE_SUCCESS';
export const MOVIE_RATE_FAILURE = 'MOVIE_RATE_FAILURE';

export const MOVIE_DELETE_RATING = 'MOVIE_DELETE_RATING';
export const MOVIE_DELETE_RATING_SUCCESS = 'MOVIE_DELETE_RATING_SUCCESS';
export const MOVIE_DELETE_RATING_FAILURE = 'MOVIE_DELETE_RATING_FAILURE';