export const PERSON_DETAIL_CLEAR = 'PERSON_DETAIL_CLEAR';
export const PERSON_DETAIL_GET_REQUEST = 'PERSON_DETAIL_GET_REQUEST';
export const PERSON_DETAIL_GET_SUCCESS = 'PERSON_DETAIL_GET_SUCCESS';
export const PERSON_DETAIL_GET_FAILURE = 'PERSON_DETAIL_GET_FAILURE';
export const PERSON_RELATED_GET_REQUEST = 'PERSON_RELATED_GET_REQUEST';
export const PERSON_RELATED_GET_SUCCESS = 'PERSON_RELATED_GET_SUCCESS';
export const PERSON_RELATED_GET_FAILURE = 'PERSON_RELATED_GET_FAILURE';